name: Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v -o gobbl ./...
      
  release:
      name: Release
      runs-on: ubuntu-latest
      steps:
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_release_rules: fix:patch,feature:minor,ver:major
            
        - name: Create a GitHub release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}
            
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
            
        - name: Package binary
          run: |
            ls -l
            tar -czvf gobbl-linux-x64-${{ steps.get_version.outputs.VERSION }}.tar.gz gobbl
          
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: gobbl-linux-x64-${{ steps.get_version.outputs.VERSION }}.tar.gz
            asset_name: "gobbl v${{ steps.get_version.outputs.VERSION }}"
            tag: ${{ github.ref }}
            overwrite: true
            body: "This is my release text"

